name: CICD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app
 
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: /home/dirempum/node.directwebhost.com
          remote_host: ${{ secrets.NODE_DIRECTWEBHOST_HOST }}
          remote_user: ${{ secrets.NODE_DIRECTWEBHOST_USER_NAME }}
          remote_key: ${{ secrets.NODE_DIRECTWEBHOST_PASSWORD }}

